# Azure Pipelines configuration file for Continuous Integration
# for building the package and running the tests under Windows.

jobs:
  - job: "Default"
    pool:
      vmImage: "windows-latest"
    strategy:
      maxParallel: 10
      matrix:
        Python313-x64:
          PYTHON_VERSION: "3.13"
          ARCH: "x64"
    continueOnError: false
    timeoutInMinutes: 60

    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: "$(PYTHON_VERSION)"
          architecture: "$(ARCH)"
        name: python

      - bash: |
          set -ex
          PYTHON="$(python.pythonLocation)\\python.exe"

          # Update pip
          $PYTHON -m pip install -U pip

          # Check that we have the expected version and architecture for Python
          $PYTHON --version
          $PYTHON -m pip --version
          $PYTHON -c "import struct; print('Void pointer width is', struct.calcsize('P') * 8)"

          # Install the build and runtime dependencies of the project
          $PYTHON -m pip install ${PIP_FLAGS} -r requirements.txt
          $PYTHON -m pip list

        displayName: "Pre-installation"

      - bash: |
          set -ex
          PYTHON="$(python.pythonLocation)\\python.exe"
          export OPENBLAS_VERBOSE=2
          echo "Numpy OpenBLAS"
          $PYTHON -c "import numpy"
          echo "Scipy OpenBLAS"
          $PYTHON -c "import scipy"

      - bash: |
          set -ex
          export OPENBLAS_VERBOSE=2
          # export OPENBLAS_CORETYPE=Haswell
          PYTHON="$(python.pythonLocation)\\python.exe"

          # Run the reproducer.
          $PYTHON run_repro.py

        displayName: "Testing"
